# SPDX-FileCopyrightText: 2024 Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "agora"
SPDX-PackageSupplier = "Nextcloud <info@vinimoz.com>"
SPDX-PackageDownloadLocation = "https://github.com/vinimoz/agora"

[[annotations]]
path = [".gitattributes", ".github/CODEOWNERS", "package-lock.json", "package.json", "composer.json", "composer.lock", "**/composer.json", "**/composer.lock", ".l10nignore", "cypress/tsconfig.json", "vendor-bin/**/composer.json", "vendor-bin/**/composer.lock", ".tx/config", "tsconfig.json", "js/vendor.LICENSE.txt", "krankerl.toml", ".npmignore", ".eslintrc.json", ".tx/backport"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["screenshots/edit-inquiry.png", "screenshots/overview.png", "screenshots/share.png", "screenshots/vote.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nextcloud contributors"
SPDX-License-Identifier = "CC0-1.0"
